---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - URL=${MYDOMAIN?No domain specified!}
      - SUBDOMAINS=seafile,
        # - EXTRA_DOMAINS=
      - VALIDATION=http
      - STAGING=true
    volumes:
      - ${BASE_DIR}/swag-data:/config
      #- swag-data:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW?Database root password is missing!}
        # - MYSQL_DATABASE=seafile
        # - MYSQL_USER=seafile_user
        # - MYSQL_PASSWORD=${DB_SEAFILE_PW?Database password for seafile user is missing!}
    volumes:
      - ${BASE_DIR}/mariadb-data:/config
      #- mariadb-data:/config
    restart: unless-stopped
  borgmatic:
    image: b3vis/borgmatic
    container_name: borgmatic
    environment:
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      - ${BASE_DIR}/swag-data:/source/swag-data:ro
      #- swag-data:/source/swag-data:ro
      - ${BASE_DIR?Base directory not specified!}/borgmatic/borgmatic.d:/etc/borgmatic.d/
      - ${BASE_DIR}/borgmatic/.ssh:/root/.ssh
      - ${BASE_DIR}/borgmatic/.config/borg:/root/.config/borg
      - ${BASE_DIR}/borgmatic/.cache/borg:/root/.cache/borg
  memcached:
    image: memcached:1.6
    container_name: memcached
    entrypoint: memcached -m 256
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - ${BASE_DIR}/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=${DB_ROOT_PW?Database root password is missing!}  # Seafile will create user and database on its own
      - TIME_ZONE=${TIMEZONE?No timezone specified!}
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${MYDOMAIN}
    depends_on:
      - mariadb
      - memcached

#volumes:
#  swag-data:
#    external: false
#  mariadb-data:
#    external: false
