---
version: "2.2"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      - ddclient-data:/config
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - URL=${MYDOMAIN?No domain specified!}
      - SUBDOMAINS=seafile,
        # - EXTRA_DOMAINS=
      - VALIDATION=http
      - STAGING=true
    volumes:
      - swag-data:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW?Database root password is missing!}
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea_user
      - MYSQL_PASSWORD=${DB_GITEA_PASSWORD?gitea database password not specified!}
    volumes:
      - mariadb-data:/config
    restart: unless-stopped
  borgmatic:
    image: b3vis/borgmatic
    container_name: borgmatic
    environment:
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      # Volumes to back up:
      - ddclient-data:/source/ddclient
      - swag-data:/source/swag
      - mariadb-data:/source/mariadb
      - seafile-data:/source/seafile
      - gitea-data:/source/gitea/data
      - gitea-config:/source/gitea/config
      - radicale-data:/source/radicale/data
      - radicale-config:/source/radicale/config
      # Volumes containing borgmatic data
      - ${BASE_DIR?Base directory not specified!}/borgmatic/borgmatic.d:/etc/borgmatic.d/
      - ${BASE_DIR}/borgmatic/.ssh:/root/.ssh
      - ${BASE_DIR}/borgmatic/.config/borg:/root/.config/borg
      - ${BASE_DIR}/borgmatic/.cache/borg:/root/.cache/borg
  memcached:
    image: memcached:1.6
    container_name: memcached
    entrypoint: memcached -m 256
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - seafile-data:/shared
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=${DB_ROOT_PW?Database root password is missing!}  # Seafile will create user and database on its own
      - TIME_ZONE=${TIMEZONE?No timezone specified!}
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=${MYDOMAIN}
    depends_on:
      - mariadb
      - memcached
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea_user
      - GITEA__database__PASSWD=${DB_GITEA_PASSWORD?gitea database password not specified!}
    restart: unless-stopped
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - 5232:5232
    init: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://radicale:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - radicale-data:/data
      - radicale-config:/config
    environment:
      - UID=${PUID?PUID is not known!}
      - GID=${PGID?PGID is not known!}

volumes:
  ddclient-data:
    external: false
  swag-data:
    external: false
  mariadb-data:
    external: false
  seafile-data:
    external: false
  gitea-data:
    external: false
  gitea-config:
    external: false
  radicale-data:
    external: false
  radicale-config:
    external: false
